package ATM;
import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;

class def {public static int aid1, amnt,actotr,actmon;
    public static String an1;
    public static String url = "jdbc:ucanaccess://ac.accdb";
    public static JTextField TextBox2 = new JTextField();
    public static JButton B1 = new JButton("1");
    public static JButton B2 = new JButton("2");
    public static JButton B3 = new JButton("3");
    public static JButton B4 = new JButton("4");
    public static JButton B5 = new JButton("5");
    public static JButton B6 = new JButton("6");
    public static JButton B7 = new JButton("7");
    public static JButton B8 = new JButton("8");
    public static JButton B9 = new JButton("9");
    public static JButton B0 = new JButton("0");
    public static JButton B00 = new JButton("00");
    public static JButton BDot = new JButton(".");
    public static JButton Exit = new JButton("EXIT");
    public static JButton Clear = new JButton("CLEAR");
    public static JButton Enter = new JButton("ENTER");
    public static JButton Withdraw = new JButton("Withdraw");
    public static JButton Transfer = new JButton("Transfer");
    public static JButton Statement = new JButton("Statement");
    public static JButton BillPay = new JButton("Pay bills");
    public static JFrame GetStatement = new JFrame("Statement");
    public static JPanel Panel1 = new JPanel();
    public static JPanel Panel2 = new JPanel();
    public static JPanel Panel3 = new JPanel();
    public static JPanel Panel4 = new JPanel();
    public static JPanel PanelP1 = new JPanel();
    public static JPanel PanelP2 = new JPanel();
    public static JLabel GetAmount = new JLabel("Enter Amount : ");
    public static Font Font1 = new Font("Arial Black", Font.BOLD, 28);
    public static Font Font2 = new Font("Copperplate Gothic", Font.BOLD, 20);
    public static Font Font3 = new Font("Courier New", Font.BOLD, 25);
    public static Font Font4 = new Font("Copperplate Gothic", Font.BOLD, 30);
    public static JTextField TextBox1 = new JTextField();
    public static Border BorderType1 = BorderFactory.createRaisedBevelBorder();
    public static Border BorderType2 = BorderFactory.createLineBorder(new Color(0xFFD14A), 5, true);
    public static String Message;
    public static JButton transfer=new JButton("transfer");
    public static JButton Cancel = new JButton("Cancel");
}
